=== Sanchezifcd0210/ifcd0210/MF0491_3-Cliente/UF 1842/E4/XML/Deportistas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generado con XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="deporte">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Atletismo "/>
				<xs:enumeration value="Baloncesto"/>
				<xs:enumeration value="Futbol"/>
				<xs:enumeration value="Golf"/>
				<xs:enumeration value="NataciÃ³n"/>
				<xs:enumeration value="Tenis"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="deportista">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deporte"/>
				<xs:element ref="nombre"/>
				<xs:element ref="logro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deportistas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deportista" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="logro" type="xs:string"/>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Jesse Owens"/>
				<xs:enumeration value="Johan Cruyff"/>
				<xs:enumeration value="Mark Spitz"/>
				<xs:enumeration value="Michael Jordan"/>
				<xs:enumeration value="Rafael Nadal"/>
				<xs:enumeration value="Tiger Woods"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Sanchezifcd0210/ifcd0210/MF0491_3-Cliente/UF 1841/E2/XML/Prueba_deportistas.xml
<?xml version="1.0" encoding="UTF-8"?>
<deportistas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/IFCD0210/MF0491_3-Cliente/UF%201841/E2/Deportistas.xsd">
	<deportista>
		<deporte>Atletismo </deporte>
		<nombre>Jesse Owens</nombre>
		<logro>4 medallas de oro olímpicas</logro>
	</deportista>
	<deportista>
		<deporte>Natación</deporte>
		<nombre>Mark Spitz</nombre>
		<logro>7 medallas de oro olímpicas</logro>
	</deportista>
	<deportista>
		<deporte>Futbol</deporte>
		<nombre>Johan Cruyff</nombre>
		<logro>1 Copa de España, 4 Ligas de España, 3 Supercopas de España, 1 Recopa de Europa, 1 Copa de Europa y 1 Supercopa de Europa con Barcelona. </logro>
	</deportista>
	<deportista>
		<deporte>Baloncesto</deporte>
		<nombre>Michael Jordan</nombre>
		<logro>6 anillos de campeón de la NBA</logro>
	</deportista>
	<deportista>
		<deporte>Tenis</deporte>
		<nombre>Rafael Nadal</nombre>
		<logro>17 Grand Slam, 34 Titulos de master 1000, 20 ATP 500, 4 copa Davis y 1 medalla de oro en los juegos olímpicos</logro>
	</deportista>
	<deportista>
		<deporte>Golf</deporte>
		<nombre>Tiger Woods</nombre>
		<logro>5 masters de augusta, 3 abiertos de EEUU, 3 abiertos britanicos, 3 campeonatos de la PGA</logro>
	</deportista>
</deportistas>
